### ISSUE TITLE
1.10 RC3 My Tickets

### ISSUE THREAD

**Issue by faguilar** [osTicket/osTicket#3228]
Hi, I'm having some issues with assigned tickets, it should list only 1 ticket, but it shows me more.

![image](https://cloud.githubusercontent.com/assets/8424520/16303160/42fc96d2-391d-11e6-93b1-cfacfdd5d6ad.png)

![imagen_23_6_16_8_36_a_m__pegada_copia](https://cloud.githubusercontent.com/assets/8424520/16303416/8a21b2f8-391e-11e6-9e4e-b4b8aa982ab3.jpg)

Any ideas?

**Comment by ntozier** [comment]
Your tickets is not "your assigned tickets" it is tickets that you have access to.  Such as being directly assigned to you, being assigned to a team you are a member of, and being assigned to a department that you are a member of.

**Comment by faguilar** [comment]
If so, do you have any idea why in the top says I only have one? but actually shows me more, normally in the previous version (1.9.12) used to show me only the tickets assigned to me and in the tab "open" what corresponds to the team or department I'm member of.

**Comment by faguilar** [comment]
Any ideas? I can't see the tickets assigned to me.

**Comment by greezybacon** [comment]
In `include/staff/tickets.inc.php`, around line 103, we have in the `assigned` case, which corresponds to the `My Tickets` queue:
```php
    $tickets->filter(Q::any(array(
        'staff_id'=>$thisstaff->getId(),
        Q::all(array('staff_id' => 0, 'team_id__gt' => 0)),
    )));
```
which seems to indicate that tickets assigned to any team, but no staff member would show up. @faguilar is this what you're seeing? @protich is this correct?

**Comment by greezybacon** [comment]
This is a duplicate of #2899

**Comment by greezybacon** [comment]
This was definitely a regression from 6b76402e5af021f0a5d08923488bb947e2efaa15

**Comment by greezybacon** [comment]
It looks like the code my be incorrect if you (the staff viewing "My Tickets") is not a member of any team. Is that the case here?

**Comment by faguilar** [comment]
Hi @greezybacon yes, that's what happen, on my tickets instead of seen only the tickets assigned to me or my team, I see all the tickets assigned to any team, but not to a staff member. The only way I found to see only my tickets is enable Limit ticket access to ONLY assigned tickets on my profile, but that means I can't see all the tickets, any ideas how to fix it ? I keep trying without success yet, I was forced to switch to the RC because of the slow queries in the 1.9.12, my DB become too big I guess, because when I switch to this new version all the query become smoother, my only problem with this version is what I mention before. Thanks in advance.

**Comment by faguilar** [comment]
@greezybacon temporarily fixed by commenting one line

`//      Q::all(array('staff_id' => 0, 'team_id__gt' => 0)),
`

**Comment by ipAnything** [comment]
Hi,

Commenting the line reduced the issue, however it does not fix it.

I have "My Tickets (9)" but displays 28 tickets. If I comment the line, the heading remains the same but I now get only 4 displayed.

I noticed that the missing 5 are tickets I replied to but are assigned to the Team that I am in but they are not Assigned to any agent.

Do you have an alternative fix for this?

**Comment by chucks26** [comment]
1.10 Last release (01-11-16) here. Same problem...any hint?

Chuck26

**Comment by ntozier** [comment]
So you are running v1.10 (901e5ea)?  (Admin panel -> Dashboard -> Information)

And you have Admin panel -> Settings -> Tickets 
Assigned Tickets: and Answered Tickets: disabled?

**Comment by chucks26** [comment]
Hi ntozier,

Informazioni sul server
Versione osTicket	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
Versione MySQL	5.7.16
Versione PHP	5.6.27-1+deb.sury.org~xenial+1

I've got:
"Assigned tickets:" checked (I want only unassigned tickets in "open" queue")
"Answered tickets:" disabled.

Problems are only in "My tickets" queue, where I find tickets assigned to me and also ticket assigned to all the teams (but no agent). I would expect to find only tickets assigned to me and teams I belong.

(Sorry for my poor english).

Any suggestion?

Chuck26

**Comment by rayfoss** [comment]
Closing duplicate issue, please continue the conversation on the new thread

**Comment by ipAnything** [comment]
@rayfoss 

> Closing duplicate issue, please continue the conversation on the new thread

Which is the new Thread?

**Comment by ntozier** [comment]
He probably means the one link to back on June 25th.
https://github.com/osTicket/osTicket/issues/2899
