### ISSUE TITLE
Assigned Team list bug in "My Tickets" in 1.10r2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2899]
There is a small list bug were tickets associated with a TEAM that I am not apart of show up in "MY Tickets" its something I usually ignored but with other agents now using the system it becoming a problem.

**Comment by simonnzg** [comment]
It looks more like "My Tickets" is a list of tickets assigned to every team I'm part of, not just those assigned to ME. To see what tickets are MINE I have to go to the Open Ticket queue and sort by user.

**Comment by haraldhh** [comment]
I have this as well on 1.10-RC2. A ticket assigned to a team shows up in my "My Tickets" list, eventhough I'm not a member of that team.

**Comment by greezybacon** [comment]
This was definitely a regression from 6b76402e5af021f0a5d08923488bb947e2efaa15

**Comment by greezybacon** [comment]
It looks like the code my be incorrect if you (the staff viewing "My Tickets") is not a member of any team. Is that the case here?

**Comment by t-oster** [comment]
I can confirm this. My Tickets shows a Ticket of a team, which I am not part of.
